#CRAN
library(tidyverse)
#Bioconductor
library(Biostrings)
library(ShortRead)

#bc_subset (generated by barcode.R) should be in the Global Environment
vr <- mclapply(bc_subset, vr_extract)

vr_count <- lapply(vr, function(x){
  i <- table(x) %>% 
    as.data.frame() %>%
    arrange(by=desc(Freq))
  i <- DataFrame(seq = AAStringSet(i[,1]), 
                 freq = i[,2])
})
vr_count


#Generating a file with all count numbers
test1 <- lapply(vr_count, function(x){
  i <- x$seq %>% Biostrings::toString() %>% 
    str_split(", ", simplify = TRUE) %>% 
    as.vector()
  data.frame(seq = i, count = x$freq)
})

for(i in 1:length(test1)){
  ifelse(i == 1, 
         j_data <<- test1[[i]], 
         j_data <<- full_join(j_data, test1[[i]], by = "seq"))
}
names(j_data) <- c("seq", names(test1))
j_data[is.na(j_data)] = 0

pj_data <- pivot_longer(j_data, -1, names_to = "barcode", values_to = "counts")

for(i in 1:length(test1)){
  write_delim(test1[[1]], 
              paste0("PRIVATE_DO_NOT_COMMIT/files/","barcode_", names(test1)[i], ".txt" ),
              col_names = FALSE)
}

